name: Package
on:
  release:
    types: [ created ]
jobs:
  package-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          chmod +x ./gradlew
      - name: package windowsUberJar
        run: ./gradlew packageReleaseUberJarForCurrentOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsUberJar
          path: build/compose/jars/*
      - name: package windowsAppImage
        run: ./gradlew packageReleaseAppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsAppImage
          path: build/compose/binaries/main-release/app/*
      - name: package windowsMsi
        run: ./gradlew packageReleaseMsi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsMsi
          path: build/compose/binaries/main-release/msi/*
      - name: package windowsExe
        run: ./gradlew packageReleaseExe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsExe
          path: build/compose/binaries/main-release/exe/*
  package-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          chmod +x ./gradlew
      - name: package linuxUberJar
        run: ./gradlew packageReleaseUberJarForCurrentOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxUberJar
          path: build/compose/jars/*
      - name: package linuxAppImage
        run: ./gradlew packageReleaseAppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxAppImage
          path: build/compose/binaries/main-release/app/*
      - name: package linuxDeb
        run: ./gradlew packageReleaseDeb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxDeb
          path: build/compose/binaries/main-release/deb/*
      - name: package linuxRpm
        run: ./gradlew packageReleaseRpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxRpm
          path: build/compose/binaries/main-release/rpm/*
  package-macos:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          chmod +x ./gradlew
      - name: package macosUberJar
        run: ./gradlew packageReleaseUberJarForCurrentOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: macosUberJar
          path: build/compose/jars/*
      - name: package macosDmg
        run: ./gradlew packageReleaseDmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: macosDmg
          path: build/compose/binaries/main-release/dmg/*
#      - name: package macosPkg
#        run: ./gradlew packageReleasePkg
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - uses: actions/upload-artifact@v4
#        with:
#          name: macosPkg
#          path: build/compose/binaries/main-release/pkg/*